### ISSUE TITLE
Create trade example

### ISSUE THREAD

**Issue by jaggedsoft** [wally-yu/binance-dex#1]
Are there examples for placing limit orders or filling existing orders?

Thank you

**Comment by wxy122221** [comment]
I have the same question.
Can't support limit order?   Right?

**Comment by wally-yu** [comment]
hi @wxy122221 and  Jon,
thanks for asking. i havn't yet support placing orders, but will definitely do it in the short future

**Comment by wxy122221** [comment]
Congratulation for you as a Binance DEX Coding Competition Winners
 Thank for your hard working!
I am forward to placing orders. 
I used sammchardy/python-binance-chain for placing orders in python 3.5.  I  tried several days but not work. @wally-yu

**Comment by bsliran** [comment]
hey @wally-yu, you have any time estimation?
